import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# 1. Load the real data generated by your Node.js script
try:
    df = pd.read_csv('overhead_benchmark.csv', index_col='Metric')
except FileNotFoundError:
    print("❌ Error: 'overhead_benchmark.csv' not found. Please run your Node.js benchmark first.")
    exit()

# Extract the rows based on the exact string matches from your Node.js script
# Note: The exact string depends on BATCH_SIZE (e.g., 'Time to Ingest 50 logs (ms)')
time_row = df.filter(like='Time to Ingest', axis=0).iloc[0]
on_chain_row = df.filter(like='On-Chain Fabric', axis=0).iloc[0]
off_chain_row = df.filter(like='Off-Chain Storage', axis=0).iloc[0]

systems = ['Plain Log', 'HashChain', 'Full On-Chain', 'Proposed MLVM']
time_values = time_row.values
on_chain_values = on_chain_row.values
off_chain_values = off_chain_row.values

# Colors for consistency
colors = ['#A9A9A9', '#4682B4', '#CD5C5C', '#2E8B57'] # Grey, Blue, Red, Green

# =========================================================
# GRAPH 1: Time Overhead (Performance)
# =========================================================
fig1, ax1 = plt.subplots(figsize=(10, 6))
bars1 = ax1.bar(systems, time_values, color=colors, edgecolor='black', width=0.6)

ax1.set_title('Performance: Time Overhead for Ingesting 50 Logs', fontsize=14, fontweight='bold')
ax1.set_ylabel('Time (ms)', fontsize=12)
ax1.set_xlabel('System Architecture', fontsize=12)

# If the On-Chain time is massively larger than the others, a log scale helps visibility.
# Uncomment the line below if the smaller bars become invisible.
# ax1.set_yscale('log') 

# Add text labels on top of the bars for exact precision
for bar in bars1:
    yval = bar.get_height()
    ax1.text(bar.get_x() + bar.get_width()/2, yval + (yval*0.02), f'{yval:.2f}', 
             ha='center', va='bottom', fontsize=10, fontweight='bold')

plt.tight_layout()
fig1.savefig('overhead_time.png', dpi=300)
print("✅ Saved Performance Graph -> overhead_time.png")

# =========================================================
# GRAPH 2: Storage Overhead (Resource Allocation & Scalability)
# =========================================================
fig2, ax2 = plt.subplots(figsize=(10, 6))

# We use a stacked bar chart to show Off-Chain vs On-Chain allocation
p1 = ax2.bar(systems, off_chain_values, color='#87CEFA', edgecolor='black', width=0.6, label='Off-Chain (Local/Redis)')
p2 = ax2.bar(systems, on_chain_values, bottom=off_chain_values, color='#FF6347', edgecolor='black', width=0.6, label='On-Chain (Fabric StateDB)')

ax2.set_title('Scalability: Storage Overhead per Batch (50 Logs)', fontsize=14, fontweight='bold')
ax2.set_ylabel('Storage Size (Bytes)', fontsize=12)
ax2.set_xlabel('System Architecture', fontsize=12)
ax2.legend(fontsize=11)

# Add text labels indicating total bytes
total_values = off_chain_values + on_chain_values
for i, total in enumerate(total_values):
    ax2.text(i, total + (max(total_values)*0.02), f'{int(total):,} B', 
             ha='center', va='bottom', fontsize=10, fontweight='bold')

plt.tight_layout()
fig2.savefig('overhead_storage.png', dpi=300)
print("✅ Saved Scalability Graph -> overhead_storage.png")